require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TimeBlocksController do

  # This should return the minimal set of attributes required to create a valid
  # TimeBlock. As you add validations to TimeBlock, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TimeBlocksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all time_blocks as @time_blocks" do
      time_block = TimeBlock.create! valid_attributes
      get :index, {}, valid_session
      assigns(:time_blocks).should eq([time_block])
    end
  end

  describe "GET show" do
    it "assigns the requested time_block as @time_block" do
      time_block = TimeBlock.create! valid_attributes
      get :show, {:id => time_block.to_param}, valid_session
      assigns(:time_block).should eq(time_block)
    end
  end

  describe "GET new" do
    it "assigns a new time_block as @time_block" do
      get :new, {}, valid_session
      assigns(:time_block).should be_a_new(TimeBlock)
    end
  end

  describe "GET edit" do
    it "assigns the requested time_block as @time_block" do
      time_block = TimeBlock.create! valid_attributes
      get :edit, {:id => time_block.to_param}, valid_session
      assigns(:time_block).should eq(time_block)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TimeBlock" do
        expect {
          post :create, {:time_block => valid_attributes}, valid_session
        }.to change(TimeBlock, :count).by(1)
      end

      it "assigns a newly created time_block as @time_block" do
        post :create, {:time_block => valid_attributes}, valid_session
        assigns(:time_block).should be_a(TimeBlock)
        assigns(:time_block).should be_persisted
      end

      it "redirects to the created time_block" do
        post :create, {:time_block => valid_attributes}, valid_session
        response.should redirect_to(TimeBlock.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved time_block as @time_block" do
        # Trigger the behavior that occurs when invalid params are submitted
        TimeBlock.any_instance.stub(:save).and_return(false)
        post :create, {:time_block => {  }}, valid_session
        assigns(:time_block).should be_a_new(TimeBlock)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TimeBlock.any_instance.stub(:save).and_return(false)
        post :create, {:time_block => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested time_block" do
        time_block = TimeBlock.create! valid_attributes
        # Assuming there are no other time_blocks in the database, this
        # specifies that the TimeBlock created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TimeBlock.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => time_block.to_param, :time_block => { "these" => "params" }}, valid_session
      end

      it "assigns the requested time_block as @time_block" do
        time_block = TimeBlock.create! valid_attributes
        put :update, {:id => time_block.to_param, :time_block => valid_attributes}, valid_session
        assigns(:time_block).should eq(time_block)
      end

      it "redirects to the time_block" do
        time_block = TimeBlock.create! valid_attributes
        put :update, {:id => time_block.to_param, :time_block => valid_attributes}, valid_session
        response.should redirect_to(time_block)
      end
    end

    describe "with invalid params" do
      it "assigns the time_block as @time_block" do
        time_block = TimeBlock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TimeBlock.any_instance.stub(:save).and_return(false)
        put :update, {:id => time_block.to_param, :time_block => {  }}, valid_session
        assigns(:time_block).should eq(time_block)
      end

      it "re-renders the 'edit' template" do
        time_block = TimeBlock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TimeBlock.any_instance.stub(:save).and_return(false)
        put :update, {:id => time_block.to_param, :time_block => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested time_block" do
      time_block = TimeBlock.create! valid_attributes
      expect {
        delete :destroy, {:id => time_block.to_param}, valid_session
      }.to change(TimeBlock, :count).by(-1)
    end

    it "redirects to the time_blocks list" do
      time_block = TimeBlock.create! valid_attributes
      delete :destroy, {:id => time_block.to_param}, valid_session
      response.should redirect_to(time_blocks_url)
    end
  end

end
